FROM gcr.io/asylo-framework/asylo

WORKDIR /workdir

COPY . /workdir

RUN ["bazel", "build", "//hello_world:hello_world_sgx_sim"]

RUN ["bazel", "run", "//hello_world:hello_world_sgx_sim", "--", "--names=World!"]

ENTRYPOINT ["./bazel-bin/hello_world/hello_world_sgx_sim"]

CMD ["World!"]
