FROM ubuntu:latest

WORKDIR /

COPY . .

# ENV IN_TOTO_LINK_CMD_EXEC_TIMEOUT='10000'

RUN apt-get update && apt-get install in-toto -y

RUN apt-get install python3

RUN apt-get install python3-pip -y

RUN apt-get install git -y

RUN apt install wget -y

RUN wget https://github.com/in-toto/in-toto/releases/download/v1.1.1/in-toto-1.1.1.tar.gz

RUN tar -xvf in-toto-1.1.1.tar.gz

WORKDIR /in-toto-1.1.1

RUN python3 setup.py build && python3 setup.py install

WORKDIR /
