apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: "misaelvf2"
  - name: GitHubUser
    value: "misaelvf2"
  - name: GitHubRepo
    value: "cluster-scoped-cicd"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: token
  - name: GitHubSecretStringKey
    value: secret
  - name: ExternalDomain
    value: 88a902f56595.ngrok.io
#   If you are using github enterprise, provide a value for GitHubDomain
#  - name: GitHubDomain
#    value: git.corp.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook