apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
    - name: yamlPathToImage
      type: string
      description: |
        The path to the image to replace in the yaml manifest (arg to yq)
  workspaces:
    - name: input
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: test-in-toto
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        cat $(workspaces.input.path)/build_push.bd562add.link
        cat $(workspaces.input.path)/develop.88a5704a.link
    - name: replace-image
      image: mikefarah/yq:3.4.1
      command: ["yq"]
      args:
        - "w"
        - "-i"
        - "$(params.path)"
        - "$(params.yamlPathToImage)"
        - "$(resources.inputs.image.url)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.path)"
