apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: secure-pipeline-run-test
spec:
  pipelineRef:
    name: secure-pipeline
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  serviceAccountName: registry-sa
  resources:
    - name: source-repo
      resourceRef:
        name: hello-world-git
    - name: image-registry
      resourceRef:
        name: hello-world-image
