apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-world-git
spec:
  type: git
  params:
    - name: revision
      value: in-toto
    - name: url
      value: https://github.com/misaelvf2/cluster-scoped-cicd
