apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secure-pipeline
spec:
  workspaces:
    - name: ws
  resources:
    - name: source-repo
      type: git
    - name: image-registry
      type: image
  tasks:
    - name: secure-build
      taskRef:
        name: build-with-asylo-and-push
      workspaces:
        - name: output
          workspace: ws
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/hybrid
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: image-registry
    - name: secure-deploy
      taskRef:
        name: deploy-using-kubectl
      workspaces:
        - name: input
          workspace: ws
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: image-registry
            from:
              - secure-build
      params:
        - name: path
          value: /workspace/source/hybrid/pod.yaml
        - name: yamlPathToImage
          value: "spec.containers[0].image"
    - name: verify
      taskRef:
        name: verify-with-in-toto
      workspaces:
        - name: metadata
          workspace: ws
      runAfter:
        - secure-deploy
