apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secure-pipeline
spec:
  workspaces:
    - name: ws
    - name: secret-ws
  resources:
    - name: source-repo
      type: git
    - name: image-registry
      type: image
  tasks:
    - name: secure-build
      taskRef:
        name: build-and-push
      workspaces:
        - name: link-metadata
          workspace: ws
        - name: build-push-key-secret
          workspace: secret-ws
      params:
        - name: pathToDockerFile
          value: /workspace/docker-source/Dockerfile #Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: image-registry
    - name: verify
      taskRef:
        name: verify-with-in-toto
      workspaces:
        - name: docker-source
          workspace: ws
      runAfter:
        - secure-build
    - name: secure-deploy
      taskRef:
        name: deploy-using-kubectl
      workspaces:
        - name: input
          workspace: ws
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: image-registry
            from:
              - secure-build
      params:
        - name: path
          value: /workspace/source/pod.yaml
        - name: yamlPathToImage
          value: "spec.containers[0].image"
      runAfter:
        - verify
